andrey-terekhov/RuC

scripts/test.sh
- Добавлена подсветка тестов с наведенными ошибками.
- Добавлена обработка 134 кода ошибки:
```
double free or corruption (!prev)
Aborted (core dumped)
```
- Добавлено динамическое описание специальных папок, текущее содержание:
```
Usage: ./test.sh [KEY] ...
Description:
This script tests all files from "../tests" directory.
Folder "../tests/errors" should contain tests with expected error.
Executable tests should be in "../tests/executable" directory.
To ignore invalid tests output, use "*/warnings/*" subdirectory.
For tests with expected runtime error, use "*/errors/*" subdirectory.
For multi-file tests, use "*/include/*" subdirectory.
Keys:
-h, --help	To output help info.
-s, --silence	For silence testing.
-d, --debug	Switch on debug tracing.
-v, --virtual	Set RuC virtual machine …
```
=> Обновление тестовой системы

.travis.yml, scripts/test.sh
- Enable Travis CI testing for Window Server, version 1809
- Disable print waiting time, because of useless & for more faster build
=> Windows CI

libs/compiler/analyzer.c, libs/compiler/analyzer.h, libs/compiler/extdecl.c, libs/compiler/syntax.c, libs/compiler/syntax.h, src/main.c
- добавлены modetab_add и modetab_get
- функции для поддержки modetab перенесены в syntax, теперь они вызываются только оттуда
- startmode перенесен в syntax, он там нужнее
- extdecl больше не обращется напрямую к modetab, используются только modetab_add, modetab_get, newdecl
- newdecl оставлена только для удобства: для нее не нужно каждый раз создавать массив, она принимает только записи длины 2
=> Новый интерфейс modetab

libs/preprocessor/preprocessor.c, libs/utils/workspace.c, libs/utils/workspace.h
```c
/**
*	Add ... to workspace
*
*	@param	ws		Workspace structure
*	@param	...		...
*
*	@return	... index, @c SIZE_MAX on failure
*/
size_t ws_add_file(workspace *const ws, const char *const path);
size_t ws_add_dir(workspace *const ws, const char *const path);
size_t ws_add_flag(workspace *const ws, const char *const flag);
/**
*	Get number of ...
*
*	@param	ws		Workspace structure
*
*	@return	Number of ...
*/
size_t ws_get_files_num(const workspace *const ws);
size_t ws_get_dirs_num(const workspace *const ws);
size_t ws_get_flags_num(const workspace *const ws);
```
=> Workspace update

libs/compiler/codegen.c, libs/compiler/errors.c, libs/compiler/errors.h, libs/compiler/syntax.c, libs/compiler/syntax.h, libs/compiler/tree.c, libs/compiler/tree.h, libs/utils/vector.c, libs/utils/vector.h, scripts/test.sh
- Указатель на текущую `node` перенесен в аргументы функций
- Удалены дублирующие интерфейсы `tree_*_node(syntax *sx, ...)`
- Уменьшено количество переключений `node`, функций `node_set_next(node *nd)`
- Добавлены модификаторы `static` и `const`
- Проведен рефакторинг имен:
- Улучшено именование переменных
- Названия функций приведены к одному формату
- Переименованы интерфейсы взаимодействия со структурой адресов
- Неиспользуемое поле `main`-ссылки переопределено под максимальное количество потоков VM
- Добавлена функция копирования `node`
- Обновлен интерфейс `vector_remove(vector *vec)`, для упрощения организации стека
- Введены новые флаги тестовой системы:
- `-f`, `--fast` для ускорения тестирования (отключает `Debug` тесты)
- `-r`, `--remove` для принудительного удаления папки …
=> Virtual machine codegen (pre-release)

libs/compiler/errors.c, libs/compiler/errors.h, libs/compiler/tree.c, libs/compiler/tree.h
- Удалены нерабочие ссылки на родителя
- Функция `node_set_child` заменена на `node_add_child`
- Добавлен интерфейс сохранения/восстановления узлов дерева по индексу:
```c
/**
*	Save internal node index
*
*	@param	nd			Node structure
*
*	@return	Internal index, @c SIZE_MAX on failure
*/
size_t node_save(node *const nd);
/**
*	Rebuild node by internal index
*
*	@param	tree		Tree table
*	@param	index		Internal index
*
*	@return	Rebuilt node
*/
node node_load(vector *const tree, const size_t index);
```
=> Обновление интерфейса узлов

libs/compiler/codegen.c, libs/compiler/lexer.c, libs/compiler/parser.h, libs/compiler/parser_decl.c, libs/compiler/parser_expr.c, libs/compiler/parser_stmt.c, libs/compiler/syntax.c, tests/errors/compiler/for_inner_declaration/outside_of_for_scope.c, tests/errors/compiler/outside_of_scope.c, tests/executable/cicles/for/inner_declaration.c, tests/executable/cicles/for/outside_of_inner_declaration.c
- Реализован разбор конструкции 'for' '(' declaration expression[opt] ';' expression[opt] ')' statement
- Добавлены тесты для этого
- В какой-то момент при переходе reprtab на map потерялся отлов ошибки использования идентификатора за пределами его области видимости - теперь в identab ставятся ITEM_MAX вместо 1
- Добавлен тест на области видимости идентификаторов
=> Объявления внутри for

libs/compiler/codegen.c, libs/compiler/codegen.h, libs/compiler/compiler.c, libs/compiler/lexer.c, libs/compiler/lexer.h, libs/compiler/parser.c, libs/compiler/parser.h, libs/preprocessor/environment.c, libs/preprocessor/environment.h, libs/utils/logger.c, src/main.c
- Отключен цветной вывод для Debug сборки macOS
- Добавлен флаг `-Wno` для "отключения" восстановления после ошибок
- Макросы `GENERATE_TREE` и `GENERATE_CODES` - привязаны к Debug конфигурации проекта
=> Some code clean up for Xcode

libs/compiler/errors.c, libs/compiler/errors.h, libs/compiler/llvmgen.c, libs/compiler/llvmopt.c, libs/compiler/parser.h, src/main.c
В связи с разговором 21.04.2021 представляю урезанную реализацию условий и циклов. Условные конструкции и циклы работают за исключением некоторых случаев. Следующие задачи пока не сделаны:
Данные замечания продублированы в коде в комментариях TODO. В остальном по условным выражениям и циклам всё сделано.
Также реализованы объявления и вызов функций, тоже в ограниченном варианте. Работают только функции типа void и int без аргументов. Других типов не возвращается, так как это будет реализовываться в рамках введения других типов. Передача аргументов не реализована в связи с проблемами в построении дерева [ссылка на issue в gitlab](https://gitlab.softcom.su/ruc/ruc/-/issues/127)
Также реализованы объявления статических и динамических массивов. По измерению я взял ограничение 5, но это легко …
=> Кодогенерация LLVM

libs/compiler/parser.h, libs/compiler/parser_decl.c, libs/compiler/parser_expr.c
Ошибка заключалась в том, что список инициализации оставлял после себя лишний EXPR_END. 
Теперь `parse_initializer`  вызывается только для разбора правой части объявлений и аргументов функций, для прочих использований была добавлена функция `parse_braced_initializer`, которая может быть частью частью выражения, а вызывающий сам подставит признак окончания выражения в случае необходимости.
=> Фикс дерева для списков инициализации

libs/compiler/parser_expr.c
Ошибка заключалась в том, что для разбора {}-аргументов функций вызывалась функция, которая ставила после списка expr-end. Для пользовательских функций это поведение приводило к правильному результату, для библиотечных - к лишнему expr-end в середине выражения, так как библиотечный вызов отличается от обычного: имя библиотечной функции записывается ее после аргументов
=> Фикс построения дерева для аргументов

libs/compiler/codes.c, libs/compiler/operations.h, libs/compiler/parser.h, libs/compiler/parser_decl.c, libs/compiler/parser_stmt.c
- Узел для оператора return теперь один
- Узел оператора return больше не добавляется произвольно
- Добавлен узел объявления типа [#150](https://gitlab.softcom.su/ruc/ruc/-/issues/150)
- Узлы объявлений переменных не содержат избыточной информации
=> Узлы return и объявлений

libs/utils/hash.c, libs/utils/hash.h, libs/utils/item.c, libs/utils/item.h, libs/utils/map.h, libs/utils/stack.c, libs/utils/stack.h, libs/utils/tree.c, libs/utils/tree.h, libs/utils/vector.c, libs/utils/vector.h
Добавлена поддержка типов `double` и `int64_t` в библиотеки: `item`, `vector`, `stack`, `hash`, `tree`. Изменена структура узла дерева.
=> Поддержка double и int64_t

libs/compiler/AST.c, libs/compiler/AST.h, libs/compiler/builder.c, libs/compiler/builder.h, libs/compiler/codes.c, libs/compiler/operations.h, libs/compiler/parser.h, libs/compiler/parser_expr.c, libs/compiler/syntax.c, libs/compiler/syntax.h
- Реализован интерфейс синтаксического дерева. В нем пока не хватает интерфейса для чтения типов и операторов case/default/switch, будут добавлены позже.
- Узел строки превращен в узел литерала
- Типы узлов разделены на три группы выражений, операторов и объявлений. Это позволяет не использовать default и не рассчитывать на то, что узлы выражений и операторов будут равноправными в дереве. Пример функции генерации операторов:
```c
static void emit_statement(information *const info, const node *const nd)
{
switch (statement_get_class(nd))
{
case STMT_DECL:
emit_declaration(info, nd);
return;
case STMT_LABEL:
emit_labeled_statement(info, nd);
return;
case STMT_CASE:
// TODO: case statement emission
// emit_case_statement(info, nd);
return;
case STMT_DEFAULT:
// TODO: default statement …
```
=> Интерфейс синтаксического дерева

libs/compiler/llvmgen.c, libs/compiler/llvmgen.h
Реализована работа со структурами, поля которых имеют простой тип char, int или double. Также реализована работа с указателями на такие структуры. Подтянуты изменения из ветки parser главного репозитория, откорректирован кодогенератор исходя из этих изменений.
=> Структуры и подтягивание изменений из парсера

libs/compiler/builder.c, libs/compiler/codegen.c, libs/compiler/errors.c, libs/compiler/errors.h, libs/compiler/instructions.c, libs/compiler/instructions.h, libs/compiler/lexer.c, libs/compiler/operations.c, libs/compiler/operations.h, libs/compiler/parser.c, libs/compiler/reporter.c, libs/compiler/reporter.h, libs/compiler/token.c, libs/compiler/token.h, libs/compiler/writer.c
This patch series addresses several problems when interoperating with C++.
1. error_t clashes with std::error_t.
2. Avoid GNU extensions (designated initializers) in headers.
3. Variable name "operator" clashes with C++'s "operator" keyword.
=> [#269] C++ compilation improvements

libs/compiler/AST.c, libs/compiler/AST.h, libs/compiler/parser.c, libs/compiler/writer.c
- Structure names are saved as argument [1] of type declaration nodes.
- Type declarations are created for all structures.
=> [#271] Preserve structure names

libs/compiler/mipsgen.c
Because nd is not an expression, but a statement, usage of `expression_get_type(nd)` is unacceptable and produces unexpected results, so program crashes on `assert(value->type == target->type)` in `emit_store_of_rvalue`.
Since check if return statement correct happens during tree construction, we can just set `return_lval.type = value.type`
=> Fix getting type of return statement in mipsgen

libs/compiler/mipsgen.c
Previously `prev_arg_displ` was an array of pointers, which was filled with pointer to the `tmp_arg_lvalue`, which is on stack, so instead of 6 different lvalue's, it contained only the last one, which broke data restoring after function call.
=> Fix data restoring after function call in mipsgen

libs/compiler/mipsgen.c
If we just call `displacement_add` when adding function argument to displacements table, stack size for function will increase, which is unnecessary because arguments are in registers.
So i created separate function for adding function arguments to displacements table.
Also fixed check if argumeint is register
=> Fix function arguments behaviour in mipsgen

libs/compiler/mipsgen.c
Изменён функционал функции `displacements_add` (раньше в неё передавалась информация о месте, где должно располагаться значение, теперь эта информация определяется внутри функции). Добавлена функция `displacements_set`, если необходимо внести в таблицу переменную с указанием места, где она располагается (например, нужно при объявлении аргументов внутри функции).
=> Create displacements_set function, change displacement_add function in mipsgen

libs/compiler/mipsgen.c
Для того, чтобы иметь возможность получать аргументы функции со стека, необходимо на момент объявления аргументов знать точный сдвиг $fp относительно значения $sp до вызова функции. Поскольку обработка тела функции (и, соответственно, вычисление размера статики) происходят после объявления аргументов, я решил изменить положение статики функции относительно $fp (как показано на изображениях ниже).
Я вижу только две альтернативы - объявлять аргументы после обработки тела (но тогда возникнут проблемы при использовании аргументов) или вычислять размер статики до объявления аргументов (что потребует двойной обход тела функции).
Как данные были расположены на стеке до изменений:
Как данные расположены на стеке после изменений:
Не PR, а драфт, потому что предполагает наличие изменений из #359, …
=> Add support for more than four function arguments in mipsgen

.github/workflows/virtual.yml, libs/compiler/builder.c, libs/compiler/builder.h, libs/compiler/codegen.c, libs/compiler/errors.c, libs/compiler/errors.h, libs/compiler/llvmgen.c, libs/compiler/mipsgen.c, libs/compiler/parser.c, libs/compiler/syntax.c, libs/compiler/syntax.h, libs/compiler/token.h, libs/compiler/writer.c, tests/semantics/assign_to_const.c, tests/semantics/function_type_const.c, tests/semantics/invalid_const_pointer_cast.c, tests/semantics/multiple_const_in_type.c
Реализован модификатор `const`. Использование:
- Не больше одного модификатора только перед типом
- Не больше одного модификатора после звездочки, перед именем переменной
=> Const type modifier

libs/compiler/mipsgen.c
Исправил очистку выражений и операцию использующуюся для перехода в различные части тернарного выражения
=> Fixed ternary expression
