andrey-terekhov/RuC

libs/compiler/extdecl.c
libs/compiler/syntax.c
libs/compiler/syntax.h

- Добавлен интерфейс для functions
- Теперь extdecl использует интерфейс, а не обращается напрямую

Functions interface

---

libs/compiler/syntax.h
libs/utils/map.c
libs/utils/map.h
libs/utils/uniio.c
libs/utils/uniscanner.c
libs/utils/uniscanner.h

`map_add`, `map_add_by_io`
Возвращают индекс ключа, если запись произведена успешно. Если ключ уже записан с другим значением, то возвращается `SIZE_MAX`, если пара ключ-значение идентична существующей, то возвращается индекс существующей.
`map_set`, `map_set_by_io`, `map_set_at`
Возвращают индекс существующего ключа при успешном изменении значения. Если ключ не существовал, или индекс некорректный то возвращается `SIZE_MAX`.
`map_get`, `map_get_by_io`, `map_get_at`
Возвращают значение пары. Если ключ не существует, или индекс некорректный, возвращается `INT_MAX`.
`map_*_by_io`
Имеют параметр `last`, в который записывается последний считанный символ. Если `last == NULL`, то ошибка.

Реализована библиотека map.h

---

libs/compiler/compiler.c
libs/preprocessor/preprocessor.c
libs/utils/CMakeLists.txt
libs/utils/item.c
libs/utils/item.h
libs/utils/map.c
libs/utils/map.h
libs/utils/vector.c
libs/utils/vector.h

- Создана библиотека `item.h`
- Добавлена возможность работы с ключoм типа `char32_t` в `map`
- Реализована функция получения ключа по индексу
- Инициализация значений в `vector_increase` нулями
- Исправлена ошибка с отсутствие входного файла, проверка `ws_get_files_num(ws) == 0`

Fix table types

---

libs/compiler/syntax.c
libs/compiler/tree.c
libs/compiler/tree.h

Реализована и интегрирована:
```c
/**
*	Set next node to the same one from tree traversal in pre-order (NLR)
*
*	@param	nd		Current node
*
*	@return	@c 0 on success, @c -1 on failure
*/
int node_set_next(node *const nd);
```

Node set next

---

libs/compiler/compiler.c
libs/compiler/tree.c
libs/compiler/tree.h
libs/utils/uniio.c
libs/utils/uniio.h
libs/utils/workspace.c
tests/executable/arrays/define/node_order.c

- Исправлена работа с абсолютными путями
- Реализована возможность отката к предыдущей позиции в `universal_io`
- Добавлены функции модификации дерева:
- `node_swap`, с потомками
- `node_order`, без потомков

New features

---

libs/compiler/extdecl.c
libs/compiler/syntax.c
libs/utils/vector.c
libs/utils/vector.h

- Добавлена функция изменения размера `vector` на заданный
- Функции `vector_add`, `vector_increase` работают через вызов  `vector_resize`

Функция vector_resize

---

libs/compiler/parser_expr.c
tests/executable/functions/cast/float_to_int.c
tests/executable/functions/cast/int_to_float.c
tests/executable/functions/cast/origin.c

Исправлено приведение типов в инициализации массивов, и добавлены новые тесты.

Codegen fix

---

libs/compiler/errors.c
libs/compiler/errors.h
libs/compiler/parser_decl.c
tests/errors/compiler/wrong_struct/empty_struct.c

https://gitlab.softcom.su/ruc/ruc/-/issues/120

Добавлена ошибка для пустой структуры

---

libs/compiler/parser_decl.c

Исправлено построение дерева для объявления структур, а так же для инициализаторов массивов и структур

Фикс построения дерева

---

libs/compiler/codegen.c
libs/compiler/parser.c
libs/compiler/parser.h
libs/compiler/parser_decl.c
libs/compiler/parser_expr.c
libs/compiler/parser_stmt.c
libs/compiler/syntax.c
libs/compiler/syntax.h

- Имена констант перечисления типов приведены к стайлгайду
- Добавлены конструкторы типов массивов и указателей

Типы приведены к стайлгайду

---

libs/utils/map.c
libs/utils/map.h
libs/utils/uniscanner.c
libs/utils/uniscanner.h
libs/utils/utf8.c
libs/utils/utf8.h

В библиотеку [`map.h`](https://github.com/andrey-terekhov/RuC/blob/master/libs/utils/map.h) добавлена функция возврата последнего считанного ключа:
```c
/**
*	Return the last read key
*
*	@param	as				Map structure
*
*	@return	Key, @c NULL on failure
*/
const char *map_last_read(const map *const as);
```
Также добавлена функция отката последнего прочитанного символа в [`uniscanner.h`](https://github.com/andrey-terekhov/RuC/blob/master/libs/utils/uniscanner.h):
```c
/**
*	Universal function for discarding UTF-8 characters
*
*	@param	io			Universal io structure
*	@param	wchar		UTF-8 character
*
*	@return	@c 0 on success, @c -1 on failure
*/
int uni_unscan_char(universal_io *const io, const char32_t wchar);
```
Для ее реализации расширен интерфейс …

Доработки взаимодействия MAP с IO

---

libs/utils/strings.c
libs/utils/strings.h

Реализованы следующие функции:
```c
size_t strings_add(strings *const vec, const char *const str);
size_t strings_add_by_utf8(strings *const vec, const char32_t *const str);
size_t strings_add_by_vector(strings *const vec, const vector *const str);
```

Strings changes

---

libs/compiler/llvmgen.c
libs/compiler/llvmopt.c

Исправлены ошибки вызова функций без аргументов, реализован вызов функций с аргументами. Пока что аргументом функции может быть только арифметическое выражение.

Вызов функций

---

libs/compiler/llvmgen.c

Реализованы операторы управления: goto, continue и break.

Операторы управления

---

libs/compiler/llvmgen.c

Реализована работа с одномерными указателями: создать указатель, получить адрес переменной, получить значение по адресу.

Одномерные указатели

---

libs/compiler/builder.c
libs/compiler/codes.c
libs/compiler/syntax.h

- Тип и категория значения выражения перенесены обратно на места 0 и 1
- Чуть подправлена печать дерева

Быстрофикс печати дерева

---

libs/compiler/builder.c
libs/compiler/builder.h
libs/compiler/codes.c
libs/compiler/lexer.c
libs/compiler/lexer.h
libs/compiler/parser_expr.c
libs/compiler/syntax.c
libs/compiler/syntax.h

https://gitlab.softcom.su/ruc/ruc/-/issues/168
- Добавлено поле в syntax
- Добавлен интерфейс для добавления и чтения строк syntax

Использование библиотеки strings

---

libs/compiler/builder.c
libs/compiler/syntax.c
libs/compiler/syntax.h

https://gitlab.softcom.su/ruc/ruc/-/issues/174
- Реализован интерфейс чтения типов
- Новый интерфейс используется в builder.c

Интерфейс чтения типов

---

libs/utils/hash.c
libs/utils/hash.h
src/main.c

Добавлены функции:
```c
/**
*	Remove record
*
*	@param	hs				Hash table
*	@param	key				Unique key
*
*	@return	@c 0 on success, @c -1 on failure
*/
int hash_remove(hash *const hs, const item_t key);
/**
*	Remove record by index
*
*	@param	hs				Hash table
*	@param	index			Record index
*
*	@return	@c 0 on success, @c -1 on failure
*/
int hash_remove_by_index(hash *const hs, const size_t index);
```

Add hash_remove

---

libs/utils/map.c
libs/utils/map.h

Добавлены функции: 
```c
/**
*	Get index of record by key
*
*	@param	as				Map structure
*	@param	key				Unique string key
*
*	@return	Index of record, @c SIZE_MAX on failure
*/
size_t map_get_index(map *const as, const char *const key);
/**
*	Get index of record by UTF-8 key
*
*	@param	as				Map structure
*	@param	key				Unique UTF-8 string key
*
*	@return	Index of record, @c SIZE_MAX on failure
*/
size_t map_get_index_by_utf8(map *const as, const char32_t *const key);
/**
*	Get index of record by reading key from io
*
*	@param	as				Map structure
*	@param	io				Universal io structure
*	@param	last			Next character after key
*
*	@return	Index of record, @c SIZE_MAX on failure
*/
size_t map_get_index_by_io(map *const as, universal_io *const io, char32_t *const last);
```

Add map_get_index

---

libs/utils/hash.c
libs/utils/hash.h
libs/utils/map.c
libs/utils/strings.c
libs/utils/strings.h

- Добавлены проверки `index != SIZE_MAX` в `by_index` функции
- Исправлена логика `map_last_read`
- Исправлена работа `strings_remove`
- Реализована функция получения длины строки в `strings.h`:
```c
/**
*	Get string length
*
*	@param	vec				Strings vector
*	@param	index			Index
*
*	@return	String length, @c 0 on failure
*/
size_t strings_get_length(const strings *const vec, const size_t index);
```

Utils fixes

---

libs/macro/linker.c
libs/macro/linker.h
libs/macro/macro.c
libs/macro/parser.c
main.c
test.c

Исправлена библиотека `linker`.

Linker changes

---

libs/compiler/parser_decl.c

https://gitlab.softcom.su/ruc/ruc/-/issues/183

Добавлены узлы объявления параметров

---

libs/compiler/AST.c
libs/compiler/AST.h
libs/compiler/builder.c
libs/compiler/syntax.c
libs/compiler/syntax.h

- В узле выборки теперь хранится оператор и индекс поля
- Добавлена функция expression_call_get_arguments_amount()
- Добавлена функция ident_get_spelling()

Небольшие изменения в дерево

---

.github/workflows/tests.yml
libs/compiler/llvmgen.c

Reverts andrey-terekhov/RuC#198

Revert "Обработка OP_CAST и type_is_integer"

---

.github/workflows/tests.yml
libs/compiler/llvmgen.c

Реализована обработка узла OP_CAST и изменён вызов type_is_integer. А ещё подправлено тестирование, чтобы не было тестирования на исполнение.

Обработка OP_CAST и type_is_integer

---

libs/compiler/codegen.c
tests/executable/arrays/upb.c

- Исправлена ошибка
- Добавлен тест

Фикс ошибки upb

---

libs/utils/item.c

Fix restore_double

---

libs/compiler/mipsgen.c

Assignments

---

.github/workflows/tests.yml
scripts/llvm.patch
scripts/test.sh

Раньше тестирующая система проверяла только, собирается ли проект и не возникают ли ошибки или таймауты при компиляции тестов. При этом качество генерируемого кода llvm никак не проверялось. В этом запросе добавлен запуск сгенерированного кода llvm на clang, что даёт больше информации о состоянии кодогенератора.

Модификация тестирующей системы

---

.github/workflows/tests.yml
libs/compiler/llvmgen.c
scripts/llvm.patch
scripts/test.sh

Какие именно изменения, можно посмотреть по коммитам

Очень много мелких изменений

---

libs/compiler/mipsgen.c

Реализованы бинарные арифметические и битовые операции

Арифметические и битовые операции

---

libs/compiler/mipsgen.c

Реализован printf для печати значений переменных

Printf с аргументами

---

libs/compiler/AST.c
libs/compiler/AST.h
libs/compiler/builder.c
libs/compiler/builder.h
libs/compiler/codegen.c
libs/compiler/operations.h
libs/compiler/parser.c
libs/compiler/writer.c

Функции, связанные с выражением-инициализатором, переименованы для однородности

Переименование инициализатора

---

libs/compiler/AST.c
libs/compiler/AST.h
libs/compiler/builder.c
libs/compiler/builder.h
libs/compiler/codegen.c
libs/compiler/parser.c
libs/compiler/writer.c

- Добавлены assert в интерфейс дерева
- Добавлены функции для остальных литералов
- Добавлено EXPR_INVALID для корректной печати дерева в тестах с ошибками

Добавлены assert в интерфейс дерева

---

libs/compiler/AST.c
libs/compiler/AST.h
libs/compiler/builder.c
libs/compiler/builder.h
libs/compiler/codegen.c
libs/compiler/lexer.c
libs/compiler/operations.h
libs/compiler/parser.c
libs/compiler/writer.c

Reverts andrey-terekhov/RuC#247

Revert "Feature"

---

libs/compiler/AST.c
libs/compiler/AST.h
libs/compiler/builder.c
libs/compiler/builder.h
libs/compiler/codegen.c
libs/compiler/lexer.c
libs/compiler/operations.h
libs/compiler/parser.c
libs/compiler/writer.c

Reverts andrey-terekhov/RuC#248

Revert "Revert "Feature""

---

libs/compiler/mipsgen.c

Реализованы простые и сложные бинарные логические операции, а также if-else (вложенные if-else тоже должны работать)

Логические операции и if-else

---

libs/compiler/errors.c
libs/compiler/errors.h
libs/compiler/lexer.c
libs/preprocessor/linker.c
tests/errors/compiler/bad_escape_sym/escape_sym_in_printf.c
tests/errors/compiler/must_be_digit_after_exp/letter_after_exp.c
tests/errors/compiler/must_be_digit_after_exp/warnings/+_and_-_after_exp.c
tests/errors/lexer/bad_character.c
tests/errors/lexer/digit_of_another_base.c
tests/errors/lexer/empty_character_literal.c
tests/errors/lexer/exponent_has_no_digits/letter_after_exp.c
tests/errors/lexer/exponent_has_no_digits/letter_after_minus_exp.c
tests/errors/lexer/exponent_has_no_digits/letter_after_plus_exp.c
tests/errors/lexer/exponent_has_no_digits/nothing_after_exp.c
tests/errors/lexer/exponent_has_no_digits/nothing_after_minus_exp.c
tests/errors/lexer/exponent_has_no_digits/nothing_after_plus_exp.c
tests/errors/lexer/missing_terminating_apost_char.c
tests/errors/lexer/missing_terminating_quote_char.c
tests/errors/lexer/unknown_escape_sequence.c
tests/errors/lexer/unterminated_block_comment.c

- Подправлено восстановление после ошибок лексера
- Написаны тесты для каждой ошибки в отдельности, удалены дубликаты

Сортировка ошибок лексера

---

libs/compiler/compiler.c
libs/compiler/parser.c
libs/compiler/syntax.c
libs/compiler/syntax.h

Для тикета https://gitlab.softcom.su/ruc/ruc/-/issues/247 вынесены проверки линковки из парсера под проверку платформы

Проверки линковки вынесены из парсера

---

libs/compiler/AST.c
libs/compiler/AST.h
libs/compiler/errors.c
libs/compiler/instructions.c
libs/compiler/parser.c
libs/compiler/syntax.c
libs/compiler/token.c
libs/compiler/token.h

https://gitlab.softcom.su/ruc/ruc/-/issues/243

Исправления предупреждений компиляции

---

libs/compiler/syntax.c

Проверка наличия main внесена под флаг -c

Фикс проверки наличия main

---

libs/compiler/compiler.c
libs/compiler/compiler.h
libs/compiler/mipsgen.c
libs/compiler/mipsgen.h

Новый-новый мипс

---

libs/compiler/llvmgen.c
libs/utils/utf8.c

Сделано следующее:
- фикс булевых констант
- свёртка с булевыми константами
- фикс преобразования типов int-char

Некоторые исправления в llvm

---

libs/compiler/mipsgen.c

- Fix copy-initialization of structures;
- Add structures inside structures in initialization lists;

Mips Codegen - Structures Initialization 

---

libs/compiler/mipsgen.c

By calling convention, registers $a0-$a3 should be saved by caller, not by callee (and in `emit_call_expression` we actually save them before the function call), so it is unnecessary to save them at the beginning of the function

Disable saving of a0-a3 registers at the entrance to function in mipsgen

---

libs/compiler/mipsgen.c

Исправил инициализацию структуры в случае, если её поле - другая структура инициализируется переменной

Fixed structure initialisation

---

libs/compiler/mipsgen.c

Исправил загрузку адреса( ранее base reg не учитывался)

Fixed address loading

---

libs/compiler/mipsgen.c

Исправил сохранение значения на стеке

Fixed array declaration

---

libs/compiler/builder.c
libs/compiler/errors.c
libs/compiler/errors.h
libs/compiler/syntax.c
libs/compiler/syntax.h
tests/semantics/array_without_init.c
tests/semantics/const_without_init.c
tests/semantics/struct_without_init.c

- Фикс константных типов внутри структур
- Фикс ошибок для константных типов

Fix const types
